language: php

cache:
    directories:
        - vendor
        - cache
        - $HOME/.composer/cache

php:
  - 5.4
  - 5.6
  - 7.0
  - 7.1
  - 7.2

sudo: false

install:
  - travis_retry composer install --no-interaction
  - travis_retry composer update --dev

script:
  - vendor/bin/phpunit tests/HelpersTest.php ${GH_USER}@${GH_PWD}

notifications:
  email:
    recipients:
      - wilonx@163.com
    on_success: never
    on_failure: never